### 24/7 command! ###
247_on: "<:m_oke:1193111935462420531> 24/7 ëª¨ë“œê°€ **í™œì„±í™”**ë˜ì—ˆìŠµë‹ˆë‹¤."
247_off: "<:m_wrong:1193112008124530738> 24/7 ëª¨ë“œê°€ **ë¹„í™œì„±í™”**ë˜ì—ˆìŠµë‹ˆë‹¤."
247_already: "<:m_warning:1193112123757305886> 24/7 ëª¨ë“œê°€ ì´ë¯¸ **%{mode}**ì…ë‹ˆë‹¤."
247_arg_error: "<:m_wrong:1193112008124530738> ì˜ëª»ëœ 24/7 ëª¨ë“œì…ë‹ˆë‹¤. %{text}ì„(ë¥¼) ì‚¬ìš©í•´ ì£¼ì„¸ìš”."
247_no_in_voice: "<:m_wrong:1193112008124530738> ìŒì„± ì±„ë„ì— ì—†ìŠµë‹ˆë‹¤!"

### Set Language command! ###
provide_lang: "<:m_wrong:1193112008124530738> **ì˜ëª»ëœ ì–¸ì–´ì…ë‹ˆë‹¤.** `%{languages}`ì„(ë¥¼) ì‚¬ìš©í•´ ì£¼ì„¸ìš”."
lang_set: "<:m_lang:1215299274833666148> **ì–¸ì–´ê°€** `%{language}` **ë¡œ ì„¤ì •ë˜ì—ˆìŠµë‹ˆë‹¤.**"
lang_change: "<:m_lang:1215299274833666148> **ì–¸ì–´ê°€** `%{language}` **ë¡œ ë³€ê²½ë˜ì—ˆìŠµë‹ˆë‹¤.**"

### Prefix command! ###
prefix_arg: "<:m_wrong:1193112008124530738> ìœ íš¨í•œ ì ‘ë‘ì‚¬ë¥¼ ì…ë ¥í•´ ì£¼ì„¸ìš”!"
prefix_length: "<:m_wrong:1193112008124530738> **ì ‘ë‘ì‚¬ëŠ” 10ìë¥¼ ì´ˆê³¼í•  ìˆ˜ ì—†ìŠµë‹ˆë‹¤.**"
prefix_set: "<:m_magic:1204853015585226855> **ì ‘ë‘ì‚¬ê°€** `%{prefix}` **ë¡œ ì„¤ì •ë˜ì—ˆìŠµë‹ˆë‹¤.**"
prefix_change: "<:m_magic:1204853015585226855> **ì ‘ë‘ì‚¬ê°€** `%{prefix}` **ë¡œ ë³€ê²½ë˜ì—ˆìŠµë‹ˆë‹¤.**"

### Control command! ###
control_set: "<:m_switch:1196007160279203841> **í”Œë ˆì´ì–´ ì œì–´ ëª¨ë“œê°€ %{toggle}ë¡œ ì„¤ì •ë˜ì—ˆìŠµë‹ˆë‹¤.**"
control_arg_error: "<:m_wrong:1193112008124530738> ì˜ëª»ëœ ì¸ìˆ˜ì…ë‹ˆë‹¤. %{text}ì„(ë¥¼) ì‚¬ìš©í•´ ì£¼ì„¸ìš”."
control_already: "<:m_warning:1193112123757305886> ë…¸ë˜ ì•Œë¦¼ì´ ì´ë¯¸ **%{mode}**ì…ë‹ˆë‹¤."

### Redeem Premium Code command! ###
redeem_title: "í”„ë¦¬ë¯¸ì—„ ì½”ë“œ êµí™˜!"

redeem_desc: |
  <:m_switch:1196007160279203841>  **ìœ í˜•:** %{type}
  <:m_ava:1204848463083474954>  **ì´ë¦„:** %{name}
  <:m_pencil:1204848507220004944>  **í”Œëœ:** %{plan}
  <:m_created:1215293513088892979>  **ë§Œë£Œ:** %{expires}

redeem_footer: "í”„ë¦¬ë¯¸ì—„ ì½”ë“œê°€ ì„±ê³µì ìœ¼ë¡œ êµí™˜ë˜ì—ˆìŠµë‹ˆë‹¤!"
redeem_invalid_guild: "<:m_warning:1193112123757305886> ìœ íš¨í•˜ì§€ ì•ŠìŠµë‹ˆë‹¤! ì˜¬ë°”ë¥¸ guildIdë¥¼ ì‚¬ìš©í•´ ì£¼ì„¸ìš”."
redeem_invalid_user: "<:m_warning:1193112123757305886> ìœ íš¨í•˜ì§€ ì•ŠìŠµë‹ˆë‹¤! ì˜¬ë°”ë¥¸ userIdë¥¼ ì‚¬ìš©í•´ ì£¼ì„¸ìš”."
redeem_invalid_mode: "<:m_warning:1193112123757305886> ìœ íš¨í•˜ì§€ ì•ŠìŠµë‹ˆë‹¤! `guild` ë˜ëŠ” `user`ë¥¼ ì‚¬ìš©í•´ ì£¼ì„¸ìš”."
redeem_invalid: "<:m_wrong:1193112008124530738> **ìœ íš¨í•˜ì§€ ì•Šì€ í”„ë¦¬ë¯¸ì—„ ì½”ë“œì…ë‹ˆë‹¤. ìœ íš¨í•œ ì½”ë“œë¥¼ ì‚¬ìš©í•´ ì£¼ì„¸ìš”.**"
redeem_already_guild: "<:m_wrong:1193112008124530738> ì´ ê¸¸ë“œëŠ” ì´ë¯¸ **í”„ë¦¬ë¯¸ì—„**ì…ë‹ˆë‹¤."
redeem_already: "<:m_warning:1193112123757305886> **ì´ë¯¸ í”„ë¦¬ë¯¸ì—„ ì‚¬ìš©ìì…ë‹ˆë‹¤.**"

### Redeem logs ###
display_name: "ë””ìŠ¤í”Œë ˆì´ ì´ë¦„"
username: "ì‚¬ìš©ì ì´ë¦„"
createdAt: "ìƒì„±ì¼"
redeemedAt: "êµí™˜ì¼"
expiresAt: "ë§Œë£Œì¼"
plan: "í”Œëœ"
title: "í”„ë¦¬ë¯¸ì—„ ì‚¬ìš©ì êµí™˜ ì„±ê³µ"
guild_title: "í”„ë¦¬ë¯¸ì—„ ì„œë²„ êµí™˜ ì„±ê³µ"
code: "êµí™˜ ì½”ë“œ ê¸°ë¡"

### Setup Music Req command! ###
setup_arg_error: "<:m_wrong:1193112008124530738> ì˜ëª»ë˜ì—ˆìŠµë‹ˆë‹¤! %{text}ì„(ë¥¼) ì‚¬ìš©í•´ ì£¼ì„¸ìš”."
setup_enable: "<:m_warning:1193112123757305886> **ì•—! ìŒì•… ì‹œìŠ¤í…œì´ ì´ë¯¸ ì¡´ì¬í•©ë‹ˆë‹¤.**"
setup_topic: "â™ª ë…¸ë˜ë¥¼ ë¶€ë¥´ê³  ì‹¶ì€ ì‚¬ëŒì€ í•­ìƒ ë…¸ë˜ë¥¼ ì°¾ìŠµë‹ˆë‹¤. â™ª"
setup_msg: "*`ìŒì•… ì‹œìŠ¤í…œì´`* %{channel} *`ì— ì„±ê³µì ìœ¼ë¡œ ì„¤ì •ë˜ì—ˆìŠµë‹ˆë‹¤.`*\n```ì£¼ì˜: ì €ì˜ ì˜¬ë°”ë¥¸ ì‘ë™ì„ ìœ„í•´ ìƒì„±í•œ ë©”ì‹œì§€ë¥¼ ì‚­ì œí•˜ì§€ ë§ˆì„¸ìš”.```"

setup_null: |
  <:m_wrong:1193112008124530738> **ìŒì•… ì‹œìŠ¤í…œì„ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤!**
  <:m_blank:1215234569008189450><:m_info:1193100286881964104> **`%{prefix}setup`ì„(ë¥¼) ì…ë ¥í•˜ì—¬ ìš”ì²­ ì±„ë„ì„ ì„¤ì •í•´ ì£¼ì„¸ìš”.**"

setup_deleted: "*`ì„¤ì • ì±„ë„ì´ ì„±ê³µì ìœ¼ë¡œ ì‚­ì œë˜ì—ˆìŠµë‹ˆë‹¤!`*"
setup_null_inguild: "<:m_wrong:1193112008124530738> **ì´ ì„œë²„ì—ì„œ ìŒì•… ì‹œìŠ¤í…œì„ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤! ë°ì´í„° ì‚­ì œ ì¤€ë¹„ ì™„ë£Œ**"
setup_queuemsg: "**ìŒì„± ì±„ë„ì— ì°¸ì—¬í•˜ê³  ì´ë¦„ì´ë‚˜ URLì„ ì‚¬ìš©í•˜ì—¬ ì—¬ê¸°ì— ë…¸ë˜ë¥¼ ì¬ìƒí•´ ì£¼ì„¸ìš”!**"
setup_playembed_author: "í˜„ì¬ ì¬ìƒ ì¤‘ì¸ ë…¸ë˜ê°€ ì—†ìŠµë‹ˆë‹¤."

### Reset Guild command! ###
reset_data_desc: "<:m_oke:1193111935462420531> **ì´ ì„œë²„ì˜ ë°ì´í„°ë² ì´ìŠ¤ê°€ ë¦¬ì…‹ë˜ì—ˆìŠµë‹ˆë‹¤.**"

### Reset User data command! ###
reset_data_user_success: "<:m_oke:1193111935462420531> **ê·€í•˜ì˜ ê³„ì • ë°ì´í„°ê°€ ë¦¬ì…‹ë˜ì—ˆìŠµë‹ˆë‹¤.**"

### Minecraft Setup ###
status_mc_create: "*`Minecraft ìƒíƒœê°€`* %{channel} *`ì— ì„±ê³µì ìœ¼ë¡œ ì„¤ì •ë˜ì—ˆìŠµë‹ˆë‹¤.`*\n```ì£¼ì˜: ìƒíƒœëŠ” ë§¤ 1ë¶„ë§ˆë‹¤ ì—…ë°ì´íŠ¸ë©ë‹ˆë‹¤. ìƒíƒœë¥¼ ë³€ê²½í•˜ë ¤ë©´ ë¨¼ì € ì±„ë„ì„ ì‚­ì œí•´ ì£¼ì„¸ìš”.```"
setup_mc_author: "Minecraft ìƒíƒœ"
setup_mc_players: "__**í”Œë ˆì´ì–´**__"
setup_mc_motd: "__**MOTD**__"
setup_mc_ip: "__**ì„œë²„ ì£¼ì†Œ**__"
setup_mc_type: "__**ìœ í˜•**__"
setup_mc_thumbnail: "https://cdn.meww.me/madebytragic/mews-mc.webp"
setup_mc_enable: |
  <:m_wrong:1193112008124530738> **ì•—! Minecraft ìƒíƒœê°€ ì´ë¯¸ ì¡´ì¬í•©ë‹ˆë‹¤.**
  <:m_blank:1215234569008189450><:m_info:1193100286881964104> **ìƒíƒœë¥¼ ë³€ê²½í•˜ë ¤ë©´ ë¨¼ì € ì±„ë„ì„ ì‚­ì œí•´ ì£¼ì„¸ìš”.**"
setup_mc_title_404: "ğŸ”´ ë°œê²¬ë˜ì§€ ì•ŠìŒ 404"
setup_mc_badrequest: "ğŸ”´ ì˜ëª»ëœ ìš”ì²­ 400"
setup_mc_offline: "ğŸ”´ ì˜¤í”„ë¼ì¸"

### Minecraft command ###
mc_ip_notfound: "ì„œë²„ ìƒíƒœë¥¼ í™•ì¸í•˜ëŠ” ë™ì•ˆ ì˜ˆê¸°ì¹˜ ì•Šì€ ì˜¤ë¥˜ê°€ ë°œìƒí–ˆìŠµë‹ˆë‹¤. ìœ íš¨í•œ IP/ì„œë²„ ì˜¨ë¼ì¸ì„ ì œê³µí•˜ê³  ë‚˜ì¤‘ì— ë‹¤ì‹œ ì‹œë„í•´ ì£¼ì„¸ìš”."
mc_ip_invalid: "**ì…ë ¥í•œ IP `%{ip}`ì´(ê°€) ìœ íš¨í•˜ì§€ ì•ŠìŠµë‹ˆë‹¤.**"

### Themes command! ###
error_themes: "<:m_wrong:1193112008124530738> ì˜ëª»ë˜ì—ˆìŠµë‹ˆë‹¤... ë‹¤ì‹œ ì‹œë„í•´ ì£¼ì„¸ìš”."
succes_themes: "**í…Œë§ˆë¥¼ %{themes}ë¡œ ì„±ê³µì ìœ¼ë¡œ ë³€ê²½í–ˆìŠµë‹ˆë‹¤.**"

### Last FM Login command! ###
lastfm_login_footer: "ì°¸ê³ : ì´ ë§í¬ëŠ” %{expired} í›„ì— ë§Œë£Œë©ë‹ˆë‹¤."
lastfm_login_title: "Last.fm ë¡œê·¸ì¸"
lastfm_login_desc: "ê·€í•˜ì˜ [Last.fm](https://www.last.fm/user/romanromannya) ê³„ì •ì— ê¶Œí•œì„ ë¶€ì—¬í•˜ì‹œê² ìŠµë‹ˆê¹Œ?\nì˜ˆë¥¼ í´ë¦­í•˜ì—¬ ì¸ì¦ í”„ë¡œì„¸ìŠ¤ë¥¼ ì‹œì‘í•´ ì£¼ì„¸ìš”."
lastfm_not_login_desc: "<:m_wrong:1193112008124530738> Last.fmì— ë¡œê·¸ì¸í•˜ì§€ ì•Šì•˜ìŠµë‹ˆë‹¤."

### Last FM Logout command! ###
lastfm_logout_title: "Last.fm ë¡œê·¸ì•„ì›ƒ"
lastfm_logout_desc: "<:m_oke:1193111935462420531> Last.fmì—ì„œ ì„±ê³µì ìœ¼ë¡œ ë¡œê·¸ì•„ì›ƒë˜ì—ˆìŠµë‹ˆë‹¤."
